### PR TITLE
Separate incompatible cards/cardpools from banned cards

### PR DESCRIPTION
**Pull request by stopfstedt**
This is a proposal to correct the technical shortcut of expressing card set incompatibilities via the banned list.

Going forward, this would get us out of the hassle of having to add newly released cards to each of the old, FFG- and Conclave-era RLs.
It would also allow us to provide better error messages to the end user in both of our deck-builders.

Finally, this would make it possible to generate human-readable restricted list output that is accurate (this only pertains to TDB at the moment).

### CODE REVIEW

**Comment by stopfstedt** [comment]
Side note: the  `cardSet` value for the packs and RLs that were issued by the Design Team should probably be changed from `redesigns` to something else, like `designteam`. 
This can be handled as a follow up item.

**Comment by ystros** [comment]
I love the idea of separating banned vs incompatible. That makes a lot of sense. 

I'm wondering if we can take this a step further. There's going to be a lot of repetition on the RLs going forward, because the original versions of redesigned cards will always be marked as "incompatible" (unless something strange is done and some of the original designs are restored?).

What if we introduce card sets as a top level concept? The RLs already have a `cardSet` property, that could reference some card set ID. Then the card set definition could list what cards are compatible or not.

**Comment by ystros** [comment]
Hit enter too fast. Could look something like this:
```json
[
    {
        "id": "original",
        "allowedCardSets": [
            "original"
        ],
        "incompatibleCards": []
    },
    {
        "id": "redesigns",
        "allowedCardSets": [
            "original",
            "redesigns"
        ],
        "incompatibleCards": [
            "01119",
            "02034",
            "02065",
            ...
        ]
    },
    {
        "id": "draft",
        "allowedCardSets": [
            "draft",
            "original"
        ]
    }
]
```

"allowedCardSet" may not be the right term. It's more like a tag on the card. The set then looks up all cards with that tag. Then you can exclude certain cards.

The other way to define this is by pack and/or cycle. But I'm not sure we want to be editing this everytime a new pack is released. And you'd still need the incompatible cards list. E.g.
```json
[
    {
        "id": "original",
        "cycles": [
            "Core",
            "westeros",
            ...
        ],
        "incompatibleCards": []
    },
    {
        "id": "redesigns",
        "cycles": [
            "Core",
            "westeros",
            ...,
            "redesigns"
            "forgotten"
        ],
        "incompatibleCards": [
            "01119",
            "02034",
            "02065",
            ...
        ]
    }
]
```

**Comment by stopfstedt** [comment]
i like the idea of defining those card sets as top level concepts.

i can think of two ways to express this. 

```json
[
    {
        "id": "original",
        "incompatibleCards": [],
        "compatibleCardSets": []
    },
    {
        "id": "redesigns",
        "incompatibleCards": [
            "01119",
            "02034",
            "02065",
            ...
        ],
        "compatibleCardSets": [
            "original"
        ],
    },
    {
        "id": "draft",
        "incompatibleCards": [],
        "compatibleCardSets": [
            "original"
        ]
    }
]
```

this is streamlined version of what you proposed in the comment above, it just eliminates the self reference (a card set is compatible with itself), and it relabels 'allowedCardSets` with `compatibleCardSets`.

the other idea is an extension of what i proposed originally, and it declares only incompatibilities between sets instead of their compatibility. sort of like a blacklist vs whitelist approach. 
the assumption is that everything is compatible unless stated otherwise.
i like that a bit better since its only deals with one of those concepts rather than both.

```json
[
    {
        "id": "original",
        "incompatibleCards": [],
        "incompatibleCardSets": [
            "redesigns"
        ]
    },
    {
        "id": "redesigns",
        "incompatibleCards": [
            "01119",
            "02034",
            "02065",
            ...
        ],
        "incompatibleCardSets": [],
    },
    {
        "id": "draft",
        "incompatibleCards": [],
        "incompatibleCardSets": [
            "redesigns"
        ]
    }
]
```

both would be workable for me.

**Comment by stopfstedt** [comment]
i'll throw something together and update this PR tonight.

**Comment by stopfstedt** [comment]
ok, updated. as suggested, i broke out the concept of card sets into it's own file. 

still waffling on whether `draft` and the other variants constitute their own sets, but it seems right so far. or at least better than lumping them in with `original` as it is now. 

so, as stated previously, all sets are compatible with each other, unless stated otherwise. compatibility is no a symmetric relationship between sets, e.g. `redesign` is compatible with `original`, but not the other way around.

i'm going to let that percolate for a bit and will try to actually build something with this in TDB, so more to come soon.

some food for thought: 

- should card set definitions be rolled into the `restricted-list.json` file, or remain in their own definition file?
- is "card set" the best term to convey what we're talking about here? other terms that may be applicable are "card block" or "card pool".

**Comment by ystros** [comment]
Not sure how I feel about the implicit "everything is compatible with everything else", but I don't think there's an example where this would be detrimental, so it's fine.

* I don't think it should live in the `restricted-list.json`. You *might* be able to make the case that the restricted lists should live in the new file, but I think it's useful to keep them separate.
* I think "card pool" is probably a better descriptor.
* Having thought about it more, I think your right about `draft`, `kingsmoot`, etc not being "card sets / pools". You could play these variants either with the FFG cards or the new era cards. So it's a different dimension. I think ultimately it should be a `format` property on a per card basis - absence implies "any" format (i.e. most cards), then set it for cards that say things like "Draft format only"

**Comment by stopfstedt** [comment]
i'm withdrawing this PR as i won't be able to work on it any time in the foreseeable future.

**Pull request closed without merging**
