### PR TITLE
Complete Dragons of the East

### PR DESCRIPTION
**Pull request by ystros**

### CODE REVIEW

**Comment by stopfstedt** [comment]
- targ events did not get spoiled, yet.
- the card id for "Pit Fighter's Blade" is an educated guess.

**Comment by ystros** [comment]
New additions look good. Water Dancer's Sword is almost certainly 15043, since neutral attachments have come between characters and events in the last box.

Will look at getting that in there + plots sometime today possibly.

**Comment by ystros** [comment]
I think that's everything we have. Missing 15022-15024 (and 15021 may not be the right code for Pit Fight's Blade)

**Comment by stopfstedt** [comment]
> I think that's everything we have. Missing 15022-15024 (and 15021 may not be the right code for Pit Fight's Blade)

added the missing three targ cards, they are all events. so the pit fighter's blade is probably in the right place.

**Comment by ystros** [comment]
Looks good to merge pending confirmation on card codes / numbers for Fire Made Flesh and Incinerate.

**Pull request merged**
