### PR TITLE
Update HMW

### PR DESCRIPTION
**Pull request by EvadLhorg**
includes latest playtesting repo changes
imageUrl properties added

todo: finalize imageUrls when the images are done

### CODE REVIEW

**Comment by stopfstedt** [comment]
loaded into dev TDB and diffed against the corresponding playtesting branch. looks good to me.
images are not loading though, the CDN responds with an access denied. not sure if that's to be expected or needs to be worked on.

**Comment by EvadLhorg** [comment]
> 
> 
> loaded into dev TDB and diffed against the `master` branch in the playtesting fork. looks good to me.
> images are not loading though, the CDN responds with an access denied. not sure if that's to be expected at this point, or needs to be worked on.

Thanks for the diff and extra pair of eyes on the issue! Yep, the imageUrls are not working yet as @ystros hasn´t uploaded the images yet. The path and filenames are based on the previous releases and the filenames on the onedrive folder where the design team shared the images.

**Comment by ystros** [comment]
Uploaded the files. Tried, at great length, to get ThronesDB running locally, but failed. The Throneteki fetchdata script was able to download all images, though, so it should be good? A bit weirded out by the spaces and punctuation in the filenames, but way too tired to bother changing them. Seems fine.

**Comment by stopfstedt** [comment]
it must have been the CDN lagging behind then. i tried again this morning, and images came through. 
updated TDB prod now - looks great! :+1: 

image

**Pull request merged**
