### PR TITLE
use the correct mace tyrell card code for the valyrian RL

### PR DESCRIPTION
**Pull request by EvadLhorg**
Use Mace Tyrell (HoT) instead of Mace Tyrell (SAT) for the valyrian restricted list

### CODE REVIEW

**Comment by stopfstedt** [comment]
are you sure? the other mace is already in the pod.

**Comment by EvadLhorg** [comment]
> 
> 
> are you sure? the other Mace (HoT) is already in the pod (Pod P2).

yep, confirmed it with Kike. I will let the people in charge of the RL .pdf file also know to fix it. In the .pdf, the version of Mace on the RL is not specified

**Comment by stopfstedt** [comment]
i think we'd have to re-work Pod P2 as well, since Mace (HoT) is now generally restricted.  

this would be the other style of pod then, with a "leading" restricted card. see 
https://thronesdb.com/restrictions#conclave2.0
for example.

**Review by stopfstedt — APPROVED** [review]
LGTM

**Pull request merged**
